name: storageGuild
description: $description
version: '${version}'

main: com.drewdrew1.Main
api-version: '26.1.2'
load: POSTWORLD
depend: [ DBManager ]
softdepend: [ Skript, PlaceholderAPI ]

authors: [ drewdrew1_ ]

commands:
  storage:
    description: Open personal or guild storage.
    aliases: [ sgstorage ]
    usage: /storage [personal|guild|expand|ticket]
  guild:
    description: Manage guilds.
    aliases: [ sgguild ]
    usage: /guild <create|invite|accept|list|storage>

permissions:
  storageguild.admin:
    description: Allows issuing storage and guild tickets.
    default: op
